# frozen_string_literal: true

plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-thread_safety

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml
  standard-minitest: config/base.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

  Include:
    - Gemfile.lint

  Exclude:
    - bin/**/*
    - vendor/**/*

Naming/PredicateMethod:
  Enabled: false

Layout/LineLength:
  Max: 199

Lint/DuplicateBranch:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

Naming/FileName:
  Exclude:
    - '*.gemspec'
    - 'lib/yard-lint.rb'
    - 'test/yard-lint_test.rb'

Naming/AccessorMethodName:
  Exclude:
    - test/support/vendors/**/*.rb

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Lint/MissingSuper:
  Enabled: false

# We use object_id often in the integration tests to check instances of objects, etc
Lint/HashCompareByIdentity:
  Exclude:
    - 'test/integrations/**/*'

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/OpenStructUse:
  Exclude:
    - 'test/**/*'

Lint/UselessAssignment:
  Exclude:
    - 'test/integrations/**/*'

Style/CommentAnnotation:
  Exclude:
    - 'test/integrations/**/*'

Lint/UselessAccessModifier:
  Exclude:
    - 'test/integrations/**/*'

Lint/UnusedMethodArgument:
  Exclude:
    - 'test/integrations/**/*'
    - 'test/fixtures/**/*'

Metrics/BlockNesting:
  Exclude:
    - bin/yard-lint

Style/SafeNavigation:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Lint/NonLocalExitFromIterator:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Performance/RedundantBlockCall:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false
