# frozen_string_literal: true

# Regression test for https://github.com/mensfeld/yard-lint/issues/128
#
# Attribute methods generated by `attr_*`, `@!attribute`, `Struct.new`, or
# `Data.define` must not be flagged by `Tags/ApiTags`. YARD's Data/Struct
# handlers hard-replace the generated methods' docstrings, stripping any
# inheritable `@api` tag from the enclosing class, and there is no YARD
# mechanism to attach per-method tags to those generated accessors.
describe 'Tags/ApiTags attribute methods' do
  attr_reader :fixture_path, :config

  before do
    @fixture_path = File.expand_path('fixtures/api_tags_attribute_methods.rb', __dir__)
    @config = test_config do |c|
      c.set_validator_config('Tags/ApiTags', 'Enabled', true)
      c.set_validator_config('Tags/ApiTags', 'AllowedApis', %w[public private])
    end
  end

  def api_tag_offenses
    Yard::Lint.run(path: fixture_path, config: config, progress: false)
              .offenses
              .select { |o| o[:name] == 'ApiTag' }
  end

  def api_tag_offense_for(object_name)
    api_tag_offenses.find { |o| o[:message].to_s.include?("`#{object_name}`") }
  end

  describe 'Data.define generated readers' do
    it 'does not flag Procedure#allow_positional_arguments' do
      assert_nil(
        api_tag_offense_for('ApiTagsAttributeExample::Procedure#allow_positional_arguments'),
        'Data.define reader should not be flagged for missing @api tag'
      )
    end

    it 'does not flag Procedure#contract' do
      assert_nil(
        api_tag_offense_for('ApiTagsAttributeExample::Procedure#contract'),
        'Data.define reader should not be flagged for missing @api tag'
      )
    end

    it 'does not flag Procedure#parameter_name' do
      assert_nil(
        api_tag_offense_for('ApiTagsAttributeExample::Procedure#parameter_name'),
        'Data.define reader should not be flagged for missing @api tag'
      )
    end
  end

  describe 'Struct.new generated accessors' do
    it 'does not flag Point#x reader' do
      assert_nil(
        api_tag_offense_for('ApiTagsAttributeExample::Point#x'),
        'Struct.new reader should not be flagged for missing @api tag'
      )
    end

    it 'does not flag Point#x= writer' do
      assert_nil(
        api_tag_offense_for('ApiTagsAttributeExample::Point#x='),
        'Struct.new writer should not be flagged for missing @api tag'
      )
    end

    it 'does not flag Point#y reader' do
      assert_nil(
        api_tag_offense_for('ApiTagsAttributeExample::Point#y'),
        'Struct.new reader should not be flagged for missing @api tag'
      )
    end

    it 'does not flag Point#y= writer' do
      assert_nil(
        api_tag_offense_for('ApiTagsAttributeExample::Point#y='),
        'Struct.new writer should not be flagged for missing @api tag'
      )
    end
  end

  describe 'attr_* generated methods' do
    it 'does not flag documented attr_reader :name' do
      assert_nil(api_tag_offense_for('ApiTagsAttributeExample#name'))
    end

    it 'does not flag documented attr_writer :age=' do
      assert_nil(api_tag_offense_for('ApiTagsAttributeExample#age='))
    end

    it 'does not flag documented attr_accessor :email reader' do
      assert_nil(api_tag_offense_for('ApiTagsAttributeExample#email'))
    end

    it 'does not flag documented attr_accessor :email= writer' do
      assert_nil(api_tag_offense_for('ApiTagsAttributeExample#email='))
    end

    it 'does not flag undocumented attr_reader :phone' do
      assert_nil(
        api_tag_offense_for('ApiTagsAttributeExample#phone'),
        'attr_reader without explicit @api tag should not be flagged'
      )
    end
  end

  describe 'non-attribute methods are still validated' do
    it 'does not flag documented regular method' do
      assert_nil(api_tag_offense_for('ApiTagsAttributeExample#summary'))
    end

    it 'flags regular method without @api tag' do
      refute_nil(
        api_tag_offense_for('ApiTagsRegularMethodExample#city'),
        'Regular methods without an explicit or inherited @api tag must still be flagged'
      )
    end

    it 'flags class without @api tag' do
      refute_nil(
        api_tag_offense_for('ApiTagsRegularMethodExample'),
        'Classes without an @api tag must still be flagged'
      )
    end
  end

  describe 'overall offense set' do
    it 'contains only the expected offenses' do
      flagged = api_tag_offenses.map { |o| o[:message] }.sort

      expected = [
        'Public object `ApiTagsRegularMethodExample` is missing @api tag',
        'Public object `ApiTagsRegularMethodExample#city` is missing @api tag'
      ].sort

      assert_equal(expected, flagged)
    end
  end
end
