# frozen_string_literal: true

# Regression fixture for https://github.com/mensfeld/yard-lint/issues/128
#
# The `Tags/ApiTags` validator must not flag attribute methods generated by
# `Data.define`, `Struct.new`, `attr_*`, or `@!attribute` directives, because
# per-method `@api` tags either flow through the declaration's docstring
# automatically or cannot be attached at all (e.g. YARD's `Data.define` handler
# creates getters whose docstring is hard-replaced, discarding any inheritable
# tags from the enclosing class).

# Holds attribute methods that must NOT be flagged by `Tags/ApiTags`.
#
# @api public
class ApiTagsAttributeExample
  # Represents a registered procedure.
  #
  # @api public
  Procedure = Data.define(:allow_positional_arguments, :contract, :parameter_name)

  # A simple coordinate.
  #
  # @api public
  Point = Struct.new(:x, :y)

  # Documented attribute reader.
  #
  # @api public
  # @return [String] user's full name
  attr_reader :name

  # Documented attribute writer.
  #
  # @api public
  # @param value [Integer] user's age
  attr_writer :age

  # Documented attribute accessor.
  #
  # @api public
  # @return [String] the email address
  attr_accessor :email

  # Undocumented attribute reader — still must not be flagged,
  # because ApiTags skips all attribute methods by design.
  attr_reader :phone

  # @!attribute [r] directive_reader
  #   Method materialized purely from a directive, with no underlying
  #   attr_reader or def. Relies on the validator's attribute skip.
  #
  #   @return [String] a value produced by the directive

  # @!attribute [rw] directive_accessor
  #   @return [Integer] a counter produced by the directive

  # Regular method documented explicitly.
  #
  # @api public
  # @return [String] summary of the example
  def summary
    "#{name} <#{email}>"
  end
end

# A plain class with no class-level api tag. Used to verify that non-attribute
# methods without explicit api tags are still flagged, so the fix does not
# silently disable the validator for ordinary methods.
class ApiTagsRegularMethodExample
  # Regular instance method without an api visibility tag.
  #
  # @return [String] the city
  def city
    'anywhere'
  end
end

# Holds an attribute method whose explicit api tag value is invalid. Used to
# verify that the attribute-method skip only suppresses *missing*-tag reports,
# not *invalid*-value reports, so typos like `publc` are still caught.
#
# @api public
class ApiTagsInvalidValueExample
  # Attribute reader with an explicit but invalid api value (typo).
  #
  # @api publc
  # @return [String] a value
  attr_reader :typo_value
end
